__title__ = 'Eadb'
__description__ = 'make adb more easy'
__url__ = 'https://github.com/wenshi11019/eadb'
__version__ = '0.1.0'
__author__ = 'DC_ing'
__author_email__ = 'dc_ing@qq.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2019 DC_ing'
